// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanAnGiaDinh.Data;

namespace QuanAnGiaDinh.Data.Migrations
{
    [DbContext(typeof(QuanAnGiaDinhDbContext))]
    [Migration("20210717065036_re-init-database")]
    partial class reinitdatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("QuanAnGiaDinh.DTOs.KhoQuan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<int?>("IdTrangThai")
                        .HasColumnType("int");

                    b.Property<int?>("MahangId")
                        .HasColumnType("int");

                    b.Property<int>("Soluong")
                        .HasColumnType("int");

                    b.Property<string>("Thucpham")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ngaynhap")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IdTrangThai");

                    b.HasIndex("MahangId");

                    b.ToTable("KhoQuans");
                });

            modelBuilder.Entity("QuanAnGiaDinh.DTOs.MaHang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<int>("Kg")
                        .HasColumnType("int");

                    b.Property<string>("LoaiHang")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MaHangs");
                });

            modelBuilder.Entity("QuanAnGiaDinh.DTOs.TrangThaiKho", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TrangThaiKhos");
                });

            modelBuilder.Entity("QuanAnGiaDinh.DTOs.KhoQuan", b =>
                {
                    b.HasOne("QuanAnGiaDinh.DTOs.TrangThaiKho", "trangThaiKho")
                        .WithMany("khoQuans")
                        .HasForeignKey("IdTrangThai");

                    b.HasOne("QuanAnGiaDinh.DTOs.MaHang", "maHang")
                        .WithMany("khoQuans")
                        .HasForeignKey("MahangId");

                    b.Navigation("maHang");

                    b.Navigation("trangThaiKho");
                });

            modelBuilder.Entity("QuanAnGiaDinh.DTOs.MaHang", b =>
                {
                    b.Navigation("khoQuans");
                });

            modelBuilder.Entity("QuanAnGiaDinh.DTOs.TrangThaiKho", b =>
                {
                    b.Navigation("khoQuans");
                });
#pragma warning restore 612, 618
        }
    }
}
